#enterprise_routers:
#- hostname: HQ-R1
#  router_id: 10.1.0.1
#  bgp:
#    enabled: True
#    asn: 100
#    peers:
#    - remote_ip: 155.1.0.1
#      remote_asn: 200
#
#  links:
#  - id: loopback 0
#    description: MGMT_IP
#    ip_addr: 10.1.0.1 255.255.255.255
#    mtu: 1500
#    nat: False
#
#  - id: eth0/0
#    description: Uplink to ISP
#    ip_addr: 155.1.0.2 255.255.255.252
#    mtu: 1500
#
#  - id: eth0/1
#    description: Downlink to FW
#    ip_addr: 10.1.1.1 255.255.255.252
#    mtu: 1500
#
#- hostname: BR1-R1
#  router_id: 10.2.0.1
#  bgp:
#    enabled: True
#    asn: 100
#    peers:
#    - remote_ip: 155.1.0.5
#      remote_asn: 200
#
#  links:
#  - id: loopback 0
#    description: MGMT_IP
#    ip_addr: 10.2.0.1 255.255.255.255
#    mtu: 1500
#    nat: False
#
#  - id: eth0/0
#    description: Uplink to ISP
#    ip_addr: 155.1.0.6 255.255.255.252
#    mtu: 1500
#
#  - id: eth0/1
#    description: Downlink to FW
#    ip_addr: 10.2.1.1 255.255.255.252
#    mtu: 1500
#
#
#
#isp_router:
#  hostname: ISP1-R1
#  router_id: 155.0.0.1
#  links:
#  - id: loopback 0
#    description: MGMT_IP
#    ip_addr: 155.0.0.1 255.255.255.255
#    mtu: 1500
#
#  - id: ethernet 0/0
#    description: Link to the cloud
#    ip_addr: dhcp
#    mtu: 1500
#
#  - id: ethernet 0/1
#    description: Link to HQ-R1
#    ip_addr: 155.1.0.1 255.255.255.252
#    mtu: 1500
#
#  - id: ethernet 0/2
#    description: Link to BR-R1
#    ip_addr: 155.1.0.5 255.255.255.252
#    mtu: 1500
#
#  bgp:
#    enabled: True
#    asn: 200
#    peers:
#    - remote_ip: 155.1.0.2
#      remote_asn: 100
#
#    - remote_ip: 155.1.0.6
#      remote_asn: 100
