enterprise_routers:
  - hostname: HQ-R1
    nat_enabled: True
    nat_external: eth0/0
    bgp_asn: 65000
    router_id: 1.1.1.1
    links:
      - id: loopback 0
        description: MGMT_IP
        ip_addr: 1.1.1.1 255.255.255.255
        mtu: 1500
        nat: False

      - id: eth0/0
        description: Uplink
        ip_addr: dhcp
        mtu: 1500
        nat: outside

      - id: eth0/1
        description: Downlink
        ip_addr: 155.0.0.1 255.255.255.0
        mtu: 1500
        nat: inside

  - hostname: BR1-R1
    nat_enabled: True
    nat_external: eth0/0
    bgp_asn: 65000
    router_id: 1.1.1.2
    links:
      - id: loopback 0
        description: MGMT_IP
        ip_addr: 1.1.1.2 255.255.255.255
        mtu: 1500
        nat: False

      - id: eth0/0
        description: Uplink
        ip_addr: dhcp
        mtu: 1500
        nat: outside

      - id: eth0/1
        description: Downlink
        ip_addr: 155.1.0.1 255.255.255.0
        mtu: 1500
        nat: inside


