---
- name: DMVPN Single Hub Config
  hosts: "R2"
  gather_facts: false
  connection: local
  
  
  vars:
   r2:
      username: admin
      password: admin
      
  tasks:

   - name: Gathering hostname for R2
     ios_command:
      commands: show run | include hostname
      provider: "{{ r2 }}"
     register: R2_HOSTNAME
     
   - name: Displaying Hostname for R2
     debug:
       msg: " displaying {{ R2_HOSTNAME.stdout_lines }}"
     
   - name: configuring tunnel 100 on R2
     ios_config:
      provider: "{{ r2 }}"
      lines:
       -  interface Tunnel 0
       -  ip address 155.1.0.2 255.255.255.0
       -  no ip redirects
       -  ip mtu 1440
       -  ip nhrp authentication cisco123
       -  ip nhrp map multicast dynamic
       -  ip nhrp map 155.1.0.1 60.0.1.1
       -  ip nhrp map multicast 60.0.1.1
       -  ip nhrp network-id 1
       -  ip nhrp nhs 155.1.0.1
       -  ip nhrp shortcut
       -  ip nhrp redirect
       -  ip ospf network point-to-multipoint
       -  ip ospf 1 area 0
       -  tunnel source Ethernet0/0
       -  tunnel mode gre multipoint
       -  tunnel key 0
