- name: New PE-R6 Interface Configuration
  hosts: "PE-R6"
  gather_facts: false
  connection: local
  

  vars:
       cli:
        username: cisco
        password: cisco

  tasks:
    - name: Pushing Interface Template
      ios_config:
       src: ./interface_template_pe.j2
       provider: "{{ cli }}"

- name: CORE-R2 PE downlink Interface Configuration
  hosts: "CORE-R2"
  gather_facts: false
  connection: local
  

  vars:
       cli:
        username: cisco
        password: cisco

  tasks:
    - name: Pushing Interface Template
      ios_config:
       src: ./interface_template_core_pe.j2
       provider: "{{ cli }}"
- name: CORE-R4 PE downlink Interface Configuration
  hosts: "CORE-R4"
  gather_facts: false
  connection: local
  

  vars:
       cli:
        username: cisco
        password: cisco

  tasks:
    - name: Pushing Interface Template
      ios_config:
       src: ./interface_template_core_pe.j2
       provider: "{{ cli }}"
