---
- name: Generating basic configuration for enterprise routers
  template: src=ent_router_config.j2 dest=config/{{ item.hostname }}.txt
  with_items:
  - "{{ hostvars['host_vars']['ent_router_configs'] }}"

#- name: Generating ISP router base configs
#  template: src=isp_router.j2 dest=config/{{ item.hostname }}.txt
#  with_items:
#  - "{{ isp_router }}"