hostname: HQ-BLD1-SW1
router_id: 10.1.0.8
vlans:
- id: 99
  name: MGMT
- id: 10
  name: MGMT_WKSTNS
links:
- id: vlan 99
  description: MGMT_IP
  link_type: l3
  ip_addr: 10.1.0.8 255.255.255.0

- id: eth0/0
  description: Uplink to CORE-SW1
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: all

- id: eth0/2
  description: Uplink to CORE-SW2
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: all

- id: eth0/1
  description: Downlink to MGMT_WKSTN_01
  switchport_mode: access
  link_type: l2
  access_vlan: 10
