hostname: HQ-DC-SW1
router_id: 10.1.0.5
vlans:
- id: 99
  name: MGMT
- id: 100
  name: SERVERS
links:
- id: vlan 99
  description: MGMT_IP
  link_type: l3
  ip_addr: 10.1.0.5 255.255.255.0

- id: vlan 100
  description: SERVERS
  link_type: l3
  ip_addr: 172.16.100.1 255.255.255.248

- id: eth0/0
  description: Uplink to CORE-SW1
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: ['1-1024']

- id: eth0/1
  description: Uplink to CORE-SW1
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: ['1-1024']

- id: eth0/2
  description: Downlink to TOR-SW1
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: ['1-1024']

- id: eth0/3
  description: Crosslink to DC-SW2
  link_type: l3
  ip_addr: 10.1.12.1 255.255.255.252