hostname: HQ-TCF-SW1
router_id: 10.1.0.9
vlans:
- id: 99
  name: MGMT
- id: 10
  name: MGMT_WKSTNS
- id: 100
  name: INSIDE_GW
links:
- id: vlan 99
  description: MGMT_IP
  link_type: l3
  ip_addr: 10.1.0.89 255.255.255.0

- id: eth0/0
  description: Uplink to CORE-FW
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: all

- id: eth0/1
  description: Downlink to CORE-SW1
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: all

- id: eth0/2
  description: Downlink to CORE-SW2
  switchport_mode: trunk
  link_type: l2
  allowed_vlans: all