---
- name: Generating basic configuration for CORE switches
  template: src=core_base.j2 dest=config/{{ item.hostname }}.txt
  with_items:
  - "{{ CORE_SWITCHES }}"

- name: Generating basic configuration for DC switches
  template: src=dc_base.jinja2 dest=config/{{ item.hostname }}.txt
  with_items:
  - "{{ DC_SWITCHES }}"

- name: Generating basic configuration for DC switches
  template: src=dc_base.jinja2 dest=config/{{ item.hostname }}.txt
  with_items:
  - "{{ TOR_SWITCHES }}"